modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="dagon_industry"
version="${file.jarVersion}"
displayName="Dagon Industry"
authors="iMikul, EnvyEnfys"
description='''

'''
[[dependencies.dagon_industry]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.dagon_industry]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
